import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1

[window.padding]
x = 18
y = 16

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
